config/routes.rb
Lsat::Application.routes.draw do

  root :to => "application#index"
  
  match 'pdfs/show/(:filename)' => 'pdfs#show'
  match ':controller/(:action)'
  match 'lesson_of_the_day' => 'lessons_collection#show'
  match 'questions_of_the_day' => 'lessons_collection#questions_of_the_day'
  match 'grade_questions_of_the_day' => 'lessons_collection#grade_questions_of_the_day'
  match 'show_vocabulary_test' => 'vocabulary_test#show'
  match 'video' => 'videos#send_video'
  match 'mp3' => 'videos#send_mp3'
  match 'take_test' => 'lsat_test#take_test'
  match 'take_timed_test' => 'lsat_test#take_timed_test'
  match 'take_timed_section' => 'lsat_test#take_timed_section'
  match 'question_text_image/:id.jpeg' => 'question#question_text_image'
  match 'show_diagnostic_test' => 'lsat_test#show_diagnostic_test'
  match 'show_diagnostic_scantron' => 'lsat_test#show_diagnostic_scantron'
  match 'grade_diagnostic_test' => 'lsat_test#grade_diagnostic_test'
  match 'signout' => 'application#signout'
  match 'create_user' => 'application#create_user'
  match 'dogpile' => 'application#create_user'
  match 'signin' => 'application#signin'
  match 'home' => 'application#home'
  match 'grade_question' => 'lsat_test#grade_question'
  match 'next_question' => 'lsat_test#next_question'
  match 'finish_test' => 'lsat_test#finish_test'

  resources :users

end

app/views/partials/_section_grading_form.html.erb
<form action="<%= grade_questions_of_the_day_path %>" method="post">
  <% @questions.lsat_sections_by_ordinal_array_objects.each_with_index do |section, s_index| %>
    <h4> SECTION <%= s_index + 1 %> </h4>
      <% section.questions_by_ordinal_array_objects.each_with_index do |question, q_index| %>
        <table>
          <tr>
            <td>
              <%= "#{q_index + 1}. " %>
            </td>
            <% ['A', 'B', 'C', 'D', 'E'].each_with_index do |answer, a_index| %>
                <td>
                  <label for="<%= q_index %>_<%= a_index %>">
                    <%= answer %>. 
                  </label>
                  <input type="radio" name="<%= section.id %>[<%= q_index %>]" value=<%="#{a_index}"%>>
                </td>
            <% end %>
        </tr>
        </table>
      <% end %>
  <% end %>
  <input type="hidden" name="test_id" value=<%="#{@questions.id}"%>>
  <input type="submit" value="Grade!">
</form>