config/routes.rb
Lsat::Application.routes.draw do

  root :to => "application#index"
  
  match 'pdfs/show/(:filename)' => 'pdfs#show'
  match ':controller/(:action)'
  match 'lesson_of_the_day' => 'lessons_collection#show'
  match 'questions_of_the_day' => 'lessons_collection#questions_of_the_day'
  match 'grade_questions_of_the_day' => 'lessons_collection#grade_questions_of_the_day'
  match 'show_vocabulary_test' => 'vocabulary_test#show'
  match 'video' => 'videos#send_video'
  match 'mp3' => 'videos#send_mp3'
  match 'take_test' => 'lsat_test#take_test'
  match 'take_timed_test' => 'lsat_test#take_timed_test'
  match 'take_timed_section' => 'lsat_test#take_timed_section'
  match 'question_text_image/:id.jpeg' => 'question#question_text_image'
  match 'show_diagnostic_test' => 'lsat_test#show_diagnostic_test'
  match 'show_diagnostic_scantron' => 'lsat_test#show_diagnostic_scantron'
  match 'grade_diagnostic_test' => 'lsat_test#grade_diagnostic_test'
  match 'signout' => 'application#signout'
  match 'create_user' => 'application#create_user'
  match 'dogpile' => 'application#create_user'
  match 'signin' => 'application#signin'
  match 'home' => 'application#home'
  match 'grade_question' => 'lsat_test#grade_question'
  match 'next_question' => 'lsat_test#next_question'
  match 'finish_test' => 'lsat_test#finish_test'

  resources :users

end

app/models/lessons_collection.rb
class LessonsCollection < ActiveRecord::Base
  # TODO this will obviously change depending on the environment
  # also these ids will be different depending on how badly the user does
  CANONICAL_LESSONS_COLLECTION_ID = 1
  LR_LESSONS_COLLECTION_ID = 1
  RC_LESSONS_COLLECTION_ID = 1
  AR_LESSONS_COLLECTION_ID = 1

  attr_accessible :user_id

  def self.set_for_user(user, scores)
    percentages = {}
    scores.each_pair do |key, val|
      num_right = val.inject(0) { |ans, sum| ans + sum }
      percentages[key] = num_right.to_f/val.size
    end
    if is_baseline?(percentages)
      lesson_ids = LessonsCollection.find(CANONICAL_LESSONS_COLLECTION_ID).lesson_ids
    else
      worst_section = percentages.min { |a, b| a[1] <=> b[1] }
      case worst_section
      when "logical_reasoning" 
        lesson_ids = LessonsCollection.find(LR_LESSONS_COLLECTION_ID).lesson_ids
      when "reading_comprehension" 
        lesson_ids = LessonsCollection.find(RC_LESSONS_COLLECTION_ID).lesson_ids
      else"reading_comprehension" 
        lesson_ids = LessonsCollection.find(AR_LESSONS_COLLECTION_ID).lesson_ids
      end
    end

    collection = LessonsCollection.new
    collection.user_id = user.id
    collection.lesson_ids = lesson_ids
    collection.current_lesson_index = 0
    collection.save
    user.save
  end

  def lesson_ids_unpacked
    @lesson_ids_unpacked ||= Marshal.load(lesson_ids)
  end

  def current_lesson_id
    lesson_ids_unpacked[current_lesson_index].to_i
  end

  private

  def self.is_baseline?(scores)
    logger.debug("BASELINE")
    logger.debug(scores)
    is_baseline_LR = scores["logical_reasoning"] >= 0.35 && scores["logical_reasoning"] <= 0.45
    is_baseline_RC = scores["reading_comprehension"] >= 0.35 && scores["logical_reasoning"] <= 0.45
    is_baseline_AR = scores["analytical_reasoning"] >= 0.35 && scores["logical_reasoning"] <= 0.45
    is_baseline_LR && is_baseline_RC && is_baseline_AR
  end
end

=begin
user = User.find(3)
scores = {}
scores["logical_reasoning"] = [0,1,0]
scores["reading_comprehension"] =  [0,1,0]
scores["analytical_reasoning"] =  [0,1,0]

LessonsCollection.set_for_user(user, scores)
=end

app/controllers/lessons_collection_controller.rb
class LessonsCollectionController < ApplicationController
  def show
    @lessons_collection = @user.lessons_collection
  end

  def questions_of_the_day
    @lesson = Lesson.find(@user.lessons_collection.current_lesson_id)
    @questions = LsatTest.find(@lesson.lsat_test_id)
  end

  def grade_questions_of_the_day
    @scores = LsatTest.grade(@user, params["test_id"], params)
    @percentages = {}
    @scores.each_pair do |key, val|
      num_right = val.inject(0) { |ans, sum| ans + sum }
      @percentages[key] = num_right.to_f/val.size
    end
    @passed = @percentages.each_value.to_a.map { |x| x > 0.5 }.include? false

    # TODO if we failed to pass we need to Do Something about it
    
  end
end

app/views/lessons_collection/questions_of_the_day.html.erb
<% content_for :head do %>
	<%= stylesheet_link_tag "lessons_collection" %>
	<%= stylesheet_link_tag "general" %>
<% end %>

<div class="grid_12">
<p>
Download and print out these questions. <%= link_to "Questions of the Day", :controller => 'pdfs', :action => 'show', :pdf => @questions.pdf %>
</p>

And when you're done, fill in your answers and get them graded. 
<%= render "partials/section_grading_form" %>
</div>

app/views/lessons_collection/show.html.erb
<% content_for :head do %>
	<%= stylesheet_link_tag "lessons_collection" %>
	<%= stylesheet_link_tag "general" %>
<% end %>

<!--
<object id="player52468167_2067282378" class="" width="100%" height="100%" type="application/x-shockwave-flash" name="player52468167_2067282378" data="http://a.vimeocdn.com/p/flash/moogaloop/5.2.52/moogaloop.swf?v=1.0.0" style="visibility: visible;">
<param name="allowscriptaccess" value="always">
<param name="allowfullscreen" value="true">
<param name="scalemode" value="noscale">
<param name="quality" value="high">
<param name="wmode" value="opaque">
<param name="bgcolor" value="#000000">
<param name="flashvars" value="server=vimeo.com&player_server=player.vimeo.com&cdn_server=a.vimeocdn.com&embed_location=http%3A%2F%2Fvimeo.com%2Fjeremyjonesfurther&force_embed=0&force_info=0&moogaloop_type=moogaloop_local&js_api=1&js_getConfig=player52468167_2067282378.getConfig&js_setConfig=player52468167_2067282378.setConfig&clip_id=52468167&fullscreen=1&js_onLoad=player52468167_2067282378.player.moogaloopLoaded&js_onThumbLoaded=player52468167_2067282378.player.moogaloopThumbLoaded">
</object>
-->
<!--
<object width="100%" height="100%" type="audio/mpeg" name="player52468167_2067282378" data="https://dl.dropbox.com/u/2074432/Jane/Tales%20From%20The%20Vienna%20Woods.mp3" style="visibility: visible;">

    <param name="controller" value="true" />
    <param name="mp3" value="mp3"/>
    <param name="autoplay" value="false" />    
</object>
<object id="player60797103_183329228" class="" width="100%" height="100%" type="application/x-shockwave-flash" name="player60797103_183329228" data="http://a.vimeocdn.com/p/flash/moogaloop/5.2.52/moogaloop.swf?v=1.0.0" style="visibility: visible;">
<param name="allowscriptaccess" value="always">
<param name="allowfullscreen" value="true">
<param name="scalemode" value="noscale">
<param name="quality" value="high">
<param name="wmode" value="opaque">
<param name="bgcolor" value="#000000">
<param name="flashvars" value="server=vimeo.com&player_server=player.vimeo.com&cdn_server=a.vimeocdn.com&embed_location=&force_embed=0&force_info=0&moogaloop_type=moogaloop_local&js_api=1&js_getConfig=player60797103_183329228.getConfig&js_setConfig=player60797103_183329228.setConfig&clip_id=60797103&fullscreen=1&js_onLoad=player60797103_183329228.player.moogaloopLoaded&js_onThumbLoaded=player60797103_183329228.player.moogaloopThumbLoaded">
</object>

-->

<div class="grid_6">
<h2>VIDEO OF THE DAY</h2>
<iframe src="http://player.vimeo.com/video/60797103" width="460" height="257" frameborder="0" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe> 
</div>
<div class="grid_6">

<h2 class="hidden">LINKS</h2>
  <table id="lesson_components">
    <tr><td><div id="questions_link"><%= link_to "Questions of the Day", questions_of_the_day_path %></td></tr>
    <tr><td><div id="vocab_link"><%= link_to "Vocabulary", show_vocabulary_test_path %></div></td></tr>
    <tr><td><div id="focus_link">Focus Game</div></td></tr>
    <tr><td><div id="reading_link">Reading of the Day</div></td></tr>
    <tr><td><div id="completion_link">Move On</div></td></tr>
  </table>
</div>