config/routes.rb
Lsat::Application.routes.draw do

  root :to => "application#index"
  
  match 'pdfs/show/(:filename)' => 'pdfs#show'
  match ':controller/(:action)'
  match 'lesson_of_the_day' => 'lessons_collection#show'
  match 'questions_of_the_day' => 'lessons_collection#questions_of_the_day'
  match 'grade_questions_of_the_day' => 'lessons_collection#grade_questions_of_the_day'
  match 'show_vocabulary_test' => 'vocabulary_test#show'
  match 'video' => 'videos#send_video'
  match 'mp3' => 'videos#send_mp3'
  match 'take_test' => 'lsat_test#take_test'
  match 'take_timed_test' => 'lsat_test#take_timed_test'
  match 'take_timed_section' => 'lsat_test#take_timed_section'
  match 'question_text_image/:id.jpeg' => 'question#question_text_image'
  match 'show_diagnostic_test' => 'lsat_test#show_diagnostic_test'
  match 'show_diagnostic_scantron' => 'lsat_test#show_diagnostic_scantron'
  match 'grade_diagnostic_test' => 'lsat_test#grade_diagnostic_test'
  match 'signout' => 'application#signout'
  match 'create_user' => 'application#create_user'
  match 'dogpile' => 'application#create_user'
  match 'signin' => 'application#signin'
  match 'home' => 'application#home'
  match 'grade_question' => 'lsat_test#grade_question'
  match 'next_question' => 'lsat_test#next_question'
  match 'finish_test' => 'lsat_test#finish_test'

  resources :users

end

app/models/lsat_test.rb
class LsatTest < ActiveRecord::Base
  has_many :lsat_sections
  attr_accessible :questions

  include SimpleHelpers

  # attr_accessible :title, :body

  # CLASS METHODS

  class << self
    # takes the user object test id, and a params hash
    def grade(user, test_id, student_answers)
      test = LsatTest.find(test_id)
      score = {}

      test.lsat_sections_by_ordinal_array_objects.each do |section|
        section_answers = student_answers[section.id.to_s]
        graded_answers = []
        section.questions_by_ordinal_array_objects.each_with_index do |question, i|
          qv = QuestionView.new
          qv.user_id = user.id
          qv.question_id = question.id
          qv.answer = section_answers[i.to_s]
          qv.save
          if question.correct_answer.to_s == section_answers[i.to_s]
            graded_answers << 1
          else
            graded_answers << 0
          end
        end
        if score[section.section_type].present?
          score[section.section_type] = score[section.section_type] + graded_answers
        else
          score[section.section_type] = graded_answers
        end
      end
      score
    end
  end

  # INSTANCE METHODS

  def is_prep_test?
    return self.prep_test_number == -1
  end

  # fix so this uses lsat section's question groups instead of questions
  def all_questions
    @all_questions ||= lsat_sections.inject([]) { |memo, obj| obj.questions + memo }
  end

  def lsat_sections_by_ordinal_array
    hash_to_ordered_array(Marshal.load(lsat_sections_by_ordinal))
  end

  def lsat_sections_by_ordinal_array_objects
    @lsat_sections_by_ordinal_array_objects ||= LsatSection.find(hash_to_ordered_array(Marshal.load(lsat_sections_by_ordinal)))
  end
end

app/controllers/lsat_test_controller.rb
class LsatTestController < ApplicationController
  # this is not a test controller
  # this controller lets you take a test

  # TODO this constant should be set in some initializer depending on the environment we're using
  DIAGNOSTIC_TEST_ID = 2

  def show_printable_test
    @test = LsatTest.find(DIAGNOSTIC_TEST_ID)
    @questions = @test.all_questions
  end

  def show_diagnostic_test
    @test = LsatTest.find(DIAGNOSTIC_TEST_ID)
  end

  def show_diagnostic_scantron
    @test = LsatTest.find(DIAGNOSTIC_TEST_ID)
    @questions = @test.all_questions
  end

  def grade_diagnostic_test
    @test = LsatTest.find(DIAGNOSTIC_TEST_ID)
    @user.taken_diagnostic = true
    @user.save
    @scores = LsatTest.grade(user, DIAGNOSTIC_TEST_ID, params)
    @percentages = {}
    @scores.each_pair do |key, val|
      num_right = val.inject(0) { |ans, sum| ans + sum }
      @percentages[key] = num_right.to_f/val.size
    end
    LessonsCollection.set_for_user(@user, @scores)
  end

  def take_timed_test
  end

  def take_timed_section
    @section = LsatSection.find(:first)
  end

  def take_test
    if params[:test_id].to_i == -1
      puts "first question"
      test = LsatTest.find(DIAGNOSTIC_TEST_ID)
      cookies[:test_id] = test.id
      cookies[:test_results] = Marshal.dump([])
      cookies[:current_test_question] = 0
      questions = test.all_questions
      cookies[:total_num_questions] = questions.size
      puts "user id overwritten?"
      puts session[:user_id]
      @question = Question.find(questions[0])
      @section = @question.lsat_section
    else
      puts "next question"
      puts session[:user_id]
      test = LsatTest.find(cookies[:test_id])
      @question = Question.find(test.all_questions[cookies[:current_test_question].to_i])
    end
  end

  def grade_question
    answer = params[:answer].to_i
    @question = Question.find(params[:question_id].to_i)
    test_results = Marshal.load(cookies[:test_results])
    test_results << [@question.id, (@question.correct_answer == params[:answer].to_i)]
    cookies[:test_results] = Marshal.dump(test_results)
    cookies[:current_test_question] = cookies[:current_test_question].to_i + 1
    if cookies[:current_test_question] == cookies[:total_num_questions].to_i
      redirect_to finish_test_path
    else
      redirect_to take_test_path
    end
  end

  def finish_test
    @test_results = Marshal.load(cookies[:test_results])
    @correct_questions = @test_results.select { |x| x[1] }
  end

  def grade_test

  end
end

app/helpers/lsat_test_helper.rb
module LsatTestHelper
  def make_presentable(str)
    str.split(/_/).map! { |x| x.capitalize }.join(" ")
  end
end

app/views/lsat_test/_question.html.erb
<!-- this is so dangerous -->
The type of question you are taking: <%= @question.question_group.lsat_section.section_type.split("_").map { |x| x.capitalize }.join(" ") %>
<br/>
<form action="<%= grade_question_path %>" method="post">
<%= @question.question_text %>
<br>
<% ['I', 'II', 'III', 'IV', 'V'].each_with_index do |numeral, index| %>
  <br>
  <input type="radio" name="answer" value=<%="#{index}"%>>
  <%= "#{numeral}. " %>
  <%= @question.unmarshaled_answers[index] %>
<% end %>
<input type="hidden" name="question_id" value="<%= @question.id %>">
<input type="submit" value="Submit">
</form>

app/views/lsat_test/_question_image.html.erb
<div id="<%= index %>" class="question_image" style="display:none">
  <%= index + 1 %>.
  <%= image_tag question.image_path, :id => "question_" + question.id.to_s %>
</div>

app/views/lsat_test/grade_diagnostic_test.html.erb
This is your score, by section:

<br/>
<br/>
<%# you shouldn't be doing this in the view, silly %>
<% @percentages.each_pair do |key, answers| %>
  <%= make_presentable(key) %>: <%= answers * 100 %>%
  <br/>
<br/>
<% end %>

<p>
Now that we've calculated your score, you can start working your way through our study schedule! <%= link_to "Begin", lesson_of_the_day_path %>

app/views/lsat_test/show_diagnostic_scantron.html.erb
Input your answer choices into this form.

<form action="<%= grade_diagnostic_test_path %>" method="post">
  <% @test.lsat_sections_by_ordinal_array_objects.each_with_index do |section, s_index| %>
    <h4> SECTION <%= s_index + 1 %> </h4>
      <% section.questions_by_ordinal_array_objects.each_with_index do |question, q_index| %>
        <table>
          <tr>
            <td>
              <%= "#{q_index + 1}. " %>
            </td>
            <% ['A', 'B', 'C', 'D', 'E'].each_with_index do |answer, a_index| %>
                <td>
                  <label for="<%= q_index %>_<%= a_index %>">
                    <%= answer %>. 
                  </label>
                  <input type="radio" name="<%= section.id %>[<%= q_index %>]" value=<%="#{a_index}"%>>
                </td>
            <% end %>
        </tr>
        </table>
      <% end %>
  <% end %>
  <input type="submit" value="Grade!">
</form>

app/views/lsat_test/show_diagnostic_test.html.erb
<% content_for :head do %>
	<%= stylesheet_link_tag "home" %>
<% end %>

Print the whole test out, follow the instructions, and then take it: <%= link_to "Diagnostic test", :controller => "pdfs", :action => "show", :pdf => @test.pdf %>. Why are we asking you to print it out, rather than doing it online? We want your first timed test to resemble actual test conditions as closely as possible, and the actual test will be on paper--not a computer screen. Once you're done, proceed to our digital scantron to get it graded: 

  <div class="clear"></div>
  <div class="grid_4 spacer"></div>
  <div class="grid_4">
    <div class="diagnose white_border">
      <%= link_to "Scantron", show_diagnostic_scantron_path %><br />
    </div>
  </div>
  <div class="grid_4 spacer"></div>
  <div class="clear"></div>

app/views/lsat_test/take_test.html.erb
<% if params[:test_id].to_i == -1 %>
Take a diagnostic test to see where you're at, before we give you a training schedule.

Here's the first question:

<% else %>

Next question:

<% end %>

<br/>
<br/>
<%= render "question" %>

app/views/lsat_test/take_timed_section.html.erb
<script type="text/javascript">
// call this every second
function updateClock(item, maxMinutes, maxSeconds, onMax) {
  var elem = $(item);
  var seconds = parseInt(elem.find(".seconds").text());
  var minutes = parseInt(elem.find(".minutes").text());

  if (maxMinutes == minutes && maxSeconds == seconds) { 
    onMax();
    return; 
  }

  seconds = seconds + 1;

  if (seconds == 60) {
    seconds = 0;
    minutes = minutes + 1;
  }

  var secondsString = seconds.toString();
  var minutesString = minutes.toString();

  if (seconds < 10 ) {
    secondsString = "0" + secondsString;
  }

  if (minutesString.length < 2) {
    minutesString = "0" + minutesString;
  }

  elem.find(".seconds").text(secondsString);
  elem.find(".minutes").text(minutesString);

}

function resetClock(elementId, handler) {
  window.clearInterval(handler);
  elem = $(elementId);
  elem.find(".seconds").text("00");
  elem.find(".minutes").text("00");
}

function startMainClock() {
  if (window.mainClockHandler == null) {
    window.mainClockHandler = window.setInterval(function () { updateClock("#main_clock", 35, 0, function() {}) }, 1000);
    /* initialize current question in some global variable */

    window.currentQuestionIndex = 0;
    $("#0").attr('style', '');
    // that anonymous function on 45 should tell student it's over. and take them to a new section

  }
}

function setQuestionClockHandler() {
    window.questionClockHandler = window.setInterval(function () { updateClock("#question_clock", 0, 15, getNewQuestion) }, 1000);
}

function getNewQuestion() {
  resetClock("#question_clock", window.questionClockHandler);
  if (window.mainClockHandler == null) { return; }
  window.clearInterval(window.questionClockHandler);
  if (window.currentQuestionIndex == window.totalQuestions - 1) {
    console.log(window.currentQuestionIndex);
    alert("you may use your remaining time to go over any question that you want");
  } else {
    var oldQuestion = window.currentQuestionIndex;
    $("#" + oldQuestion.toString()).attr('style', 'display:none');
    window.currentQuestionIndex += 1;
    $("#" + window.currentQuestionIndex.toString()).attr('style', '');
    setQuestionClockHandler();
  }
}

function startTestClock() {
  startMainClock();
  setQuestionClockHandler();
}

function storeAnswer(question, answer) {
  // store answer somehow in session
}

window.totalQuestions = <%= @section.questions.size %>

</script>

<div>
  <div id="overall">
    Click this button to start the test: <button id="start_overall_test" onclick="startTestClock();">Start!</button>
    </br>
    Time you have left for the entire test:
    <span id="main_clock"><b><span class="minutes">00</span>:<span class="seconds">00</span></b></span>
  </div>

  <div id="question_timer">
    Try a different question, if you're done with this one already, or stuck: <button id="start_question" onclick="getNewQuestion();">Move on</button>
    </br>
    Time you have left for this question:
    <span id="question_clock"><b><span class="minutes">00</span>:<span class="seconds">00</span></b></span>
  </div>

  <% @section.questions.each_with_index do |question, index| %>
    <%= render :partial => "question_image", :locals => { :index => index, :question => question } %>
  <% end %>
</div>