config/routes.rb
Lsat::Application.routes.draw do

  root :to => "application#index"
  
  match 'pdfs/show/(:filename)' => 'pdfs#show'
  match ':controller/(:action)'
  match 'lesson_of_the_day' => 'lessons_collection#show'
  match 'questions_of_the_day' => 'lessons_collection#questions_of_the_day'
  match 'grade_questions_of_the_day' => 'lessons_collection#grade_questions_of_the_day'
  match 'show_vocabulary_test' => 'vocabulary_test#show'
  match 'video' => 'videos#send_video'
  match 'mp3' => 'videos#send_mp3'
  match 'take_test' => 'lsat_test#take_test'
  match 'take_timed_test' => 'lsat_test#take_timed_test'
  match 'take_timed_section' => 'lsat_test#take_timed_section'
  match 'question_text_image/:id.jpeg' => 'question#question_text_image'
  match 'show_diagnostic_test' => 'lsat_test#show_diagnostic_test'
  match 'show_diagnostic_scantron' => 'lsat_test#show_diagnostic_scantron'
  match 'grade_diagnostic_test' => 'lsat_test#grade_diagnostic_test'
  match 'signout' => 'application#signout'
  match 'create_user' => 'application#create_user'
  match 'dogpile' => 'application#create_user'
  match 'signin' => 'application#signin'
  match 'home' => 'application#home'
  match 'grade_question' => 'lsat_test#grade_question'
  match 'next_question' => 'lsat_test#next_question'
  match 'finish_test' => 'lsat_test#finish_test'

  resources :users

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include ApplicationHelper

  before_filter :require_login, :except => [:index, :signin]
  before_filter :set_user

#  protect_from_forgery

  def index
    if user
      if !@user.taken_diagnostic
        redirect_to :action => "show_diagnostic_test", :controller => "lsat_test"
      else
        redirect_to :lesson_of_the_day
      end
    end
  end

  # remember to put in password confirmation later
  def create_user
    puts params.inspect
    # let's pretend no validations problems
    u = User.new
    u.screen_name = params[:screen_name]
    u.password = params[:password]
    u.email = params[:email]
    u.save
  end

  def home
  end

  def signin
    if User.authenticate(params[:screen_name], params[:password])
      # save in cookie
      @user = User.find_by_screen_name(params[:screen_name])
      session[:user_id] = @user.id
      redirect_to home_path
    end
  end

  def signout
    session[:user_id] = nil
    flash[:notice] = "You signed out!"
    redirect_to root_path
  end

  private

  def require_login
    redirect_to root_path if user.blank?
  end

  def set_user
    return nil if session[:user_id].blank?
    @user ||= User.find(session[:user_id].to_i)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def user
    if session[:user_id]
      User.find_by_id(session[:user_id].to_i) 
    else
      nil
    end
  end
end

app/views/application/_nav_bar.html.erb
<div class="clear"></div>
<div class="grid_4 top_nav nav_left">
  <ul class="nav-list">
    <li class="nav_border">
        <%= link_to "Home", root_path %>
    </li>
    <li class="nav_border">
        <a>Pricing</a>
    </li>
    <li class="">
      <a>About</a>
    </li>
  </ul>
</div>

  <div class="grid_4 centerpiece">
    <a href="/">
      <div style="font-size: 35px;">RENEGADE</div> 
      <div style="font-size: 35px;">LSAT PREP</div>
    </a>
  </div>

<div class="grid_4 top_nav nav_right">
  <ul class="nav-list">
    <li class="">
      <% if @user %>
        <%= link_to "Sign Out", signout_path %>
      <% else %>
        <%= link_to "Sign In", signin_path %>
      <% end %>
    </li>
    <li class="nav_border">
    <% unless @user %>
        <a><%= link_to "Sign Up", :controller => :users, :action => "show_signup_form" %></a>
    <% else %>
        <a>My Account</a>
    <% end %>
    </li>
    <li class="nav_border">
        <a>FAQ</a>
    </li>
  </ul>
</div>

<div class="clear"></div>

app/views/application/finish_test.html.erb
You got <%= @correct_questions.size %> right out of <%= @test_results.size %>.

<%= link_to "Go back home", home_path %>

app/views/application/home.html.erb
<% content_for :head do %>
	<%= stylesheet_link_tag "home" %>
	<%= stylesheet_link_tag "general" %>
<% end %>


  The first step is to take a diagnostic test and show us where you're at, so we can tweak the course schedule for you.
  <div class="clear"></div>

  <div class="grid_4 spacer"></div>

  <div class="grid_4">
    <div class="diagnose white_border">
      <%= link_to "Click on me.", show_diagnostic_test_path %>
    </div>
  </div>

app/views/application/index.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag "index"%>
<% end %>
<div class="clear"></div>

<div id="main_content">
  <div class="grid_8 ">
    <div class="ellens_face white_border">
      <img id="placeholder" src="<%= asset_path('ellen_placeholder.jpeg') %>" />
        <p style="margin: 10px; text-align: center">
          A larger placeholder image will be forthcoming.
        </p>
    </div>
  </div>
  <div class="grid_4">
    <div class="sidebar white_border" style="border-left-style:none;">
      <h3>
        FEATURING
      </h3>

      <ul>
        <li>
          Surefire methods for improving your reading comprehension skills. <!-- Warning: you'll be required to apply yourself. -->
        </li>
        <li>
          TWO hours of free tutoring from our resident expert, Miss Ellen Cassidy.
        </li>
        <li>
          Learn to focus with our unique suite of focus games (coming soon).
        </li>
        <li>
          <!-- Enlighten your poor soul through reading our carefully-curated selections from <i>The New Yorker</i> and other fine magazines. You know, the kinds of things real lawyers like to read in their precious downtime. -->
          No matter what reading level you're at right now, we'll get you up to speed.
        </li>
      </ul>

    </div>
  </div>
</div>

<div class="grid_1 spacer">
</div>

app/views/application/signin.html.erb
<% content_for :head do %>
  <%= stylesheet_link_tag "signin"%>
  <script>
  function slideDown() {
  } 
  </script>
<% end %>
<div class="clear"></div>

<div id="main_content">
  <div class="grid_4 spacer">
  </div>
  <div class="grid_4">
    <div id="form" class="white_border">
      Sign in to access your course.
      <form action="/signin" method="post">
        <span> Screen name: </span>
          <input type="text" name="screen_name" size="10" id="screen_name">
        <div id="password">
          <span id="password_label">
            Password: 
          </span>
          <input type="password" name="password" size="10"><br>
        </div>
        <br/>
        <input type="submit" value="Submit">
      </form>
    </div>
  </div>
  <div class="grid_4 spacer">
  </div>
</div>